import { FormSchema, FormField, FormRule } from '@/types/schema';
import type { ValidationRule } from '@/components/builder/CustomValidationsPanel';

/**
 * Normalizes a rule condition or group recursively.
 */
function sanitizeCondition(cond: any): any {
  if (!cond || typeof cond !== 'object') return null;

  // If it has conditions, it's a group
  if (Array.isArray(cond.conditions) || cond.type === 'group') {
    return {
      type: 'group',
      id: cond.id || crypto.randomUUID(),
      logic: cond.logic || cond.conditionLogic || 'AND',
      conditions: cond.conditions
        ? cond.conditions.map(sanitizeCondition).filter(Boolean)
        : []
    };
  }

  // Otherwise treat as a single condition
  return {
    type: 'condition',
    field: cond.field || cond.columnName || cond.field_key || '',
    operator: cond.operator || 'EQUALS',
    value: cond.value !== undefined ? cond.value : '',
    valueType: cond.valueType || 'STATIC'
  };
}

/**
 * Normalizes form logic rules.
 */
function sanitizeRules(rules: any[]): FormRule[] {
  if (!Array.isArray(rules)) return [];
  return rules.map(r => ({
    id: r.id || crypto.randomUUID(),
    name: r.name || 'Untitled Rule',
    conditionLogic: r.conditionLogic || 'AND',
    conditions: Array.isArray(r.conditions) 
      ? r.conditions.map(sanitizeCondition).filter(Boolean)
      : [],
    actions: Array.isArray(r.actions) 
      ? r.actions.map((a: any) => ({
          type: a.type || 'SHOW',
          targetField: a.targetField || a.field || '',
          message: a.message || ''
        }))
      : []
  })).filter(r => r.conditions.length > 0);
}

/**
 * Normalizes custom form validations.
 */
function sanitizeFormValidations(validations: any[]): ValidationRule[] {
  if (!Array.isArray(validations)) return [];
  return validations.map((v, idx) => ({
    id: v.id || crypto.randomUUID(),
    scope: v.scope || 'FORM',
    fieldKey: v.fieldKey || v.field || '',
    expression: v.expression || '',
    errorMessage: v.errorMessage || 'Validation failed',
    executionOrder: v.executionOrder !== undefined ? v.executionOrder : idx
  })).filter(v => v.expression);
}

function sanitizeField(f: any): FormField {
  const id = f.id || f.field_key || f.columnName || crypto.randomUUID().split('-')[0];
  const columnName = f.columnName || f.field_key || `field_${id}`;
  
  const field: FormField = {
    id: id.toString(),
    type: f.type || 'TEXT',
    label: f.label || 'Untitled Field',
    columnName: columnName,
    placeholder: f.placeholder || '',
    defaultValue: f.defaultValue || '',
    options: Array.isArray(f.options) ? f.options : undefined,
    validation: {
      required: f.validation?.required || f.is_required || false,
      min: f.validation?.min,
      max: f.validation?.max,
      pattern: f.validation?.pattern,
    },
    is_hidden: f.is_hidden || false,
    is_disabled: f.is_disabled || false,
    children: Array.isArray(f.children) ? f.children.map(sanitizeField) : undefined,
    calculationFormula: f.calculationFormula || f.formula || undefined,
  };

  return field;
}

/**
 * Sanitizes and normalizes a schema generated by AI to ensure it adheres to the 
 * strict FormSchema interface, preventing runtime errors and unique key warnings.
 */
export function sanitizeAiSchema(raw: any): FormSchema {
  if (!raw || typeof raw !== 'object') {
    throw new Error("Invalid AI schema: not an object");
  }

  return {
    id: raw.id,
    title: raw.title || 'Untitled AI Form',
    description: raw.description || '',
    fields: Array.isArray(raw.fields) ? raw.fields.map(sanitizeField) : [],
    rules: sanitizeRules(raw.rules),
    formValidations: sanitizeFormValidations(raw.formValidations),
    themeColor: raw.themeColor || '#6366f1',
    themeFont: raw.themeFont || 'Inter',
    targetTableName: raw.targetTableName || '',
    allowEditResponse: !!raw.allowEditResponse,
    status: raw.status || 'DRAFT'
  };
}
